id: A227DB3C8
title: 'Song of the Illusory Display: The Lineage Prayer for the Heart-Essence of
  the Deathless Lake-Born Vajra'
type: translation
pechas:
- I64EA65EC
- IF98ABE90
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:13.041302
  last_modified_at: 2023-01-04 12:01:13.041309
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I64EA65EC/CE05: '6098'
  IF98ABE90/E100: '6098'
